### ISSUE TITLE
[BUG]: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by Spiral-Memory** [RocketChat/EmbeddedChat#596]
### Description

If you try to integrate this `EmbeddedChat` package into a React application created using `create-react-app`, as soon as you log in, you will encounter a warning or error similar to this:

```
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at http://localhost:3002/rc-app-demo-page/static/js/bundle.js:5147:75
    at new Promise (<anonymous>)
    at t.<anonymous> (http://localhost:3002/rc-app-demo-page/static/js/bundle.js:5139:24)
    at http://localhost:3002/rc-app-demo-page/static/js/bundle.js:4962:19
    at Object.next (http://localhost:3002/rc-app-demo-page/static/js/bundle.js:4973:10)
    at http://localhost:3002/rc-app-demo-page/static/js/bundle.js:4896:35
    at new Promise (<anonymous>)
    at __awaiter$3 (http://localhost:3002/rc-app-demo-page/static/js/bundle.js:4876:12)
    at a.send (http://localhost:3002/rc-app-demo-page/static/js/bundle.js:5136:16)
    at t.<anonymous> (http://localhost:3002/rc-app-demo-page/static/js/bundle.js:5063:33)
```

A similar issue can also be found sometimes while in development, such as when Storybook hot reloads. Open the console log, and try to trigger actions like clicking on the page or typing something. You will notice a console error related to DDP:

```
Uncaught (in promise) Error: [ddp] sending without open connection
    at ddp.js:296:1
    at new Promise (<anonymous>)
    at Socket.<anonymous> (ddp.js:294:1)
    at step (ddp.js:60:1)
    at Object.next (ddp.js:41:1)
    at ddp.js:35:1
    at new Promise (<anonymous>)
    at push.../../node_modules/@rocket.chat/sdk/lib/drivers/ddp.js.__awaiter (ddp.js:31:1)
    at Socket._this.send (ddp.js:291:1)
    at Socket.<anonymous> (ddp.js:352:1)
```

![image](https://github.com/RocketChat/EmbeddedChat/assets/78961432/3b4ce409-9dbd-43f2-aaf2-ce3ee2ddb9af)

The problem most likely lies in the connect function of the app in the `EmbeddedChatAPI` file. In the connect function, after `connect({})` has been called, we call the resume function and pass the token. It seems like the connect function needs some time to establish the connection, and only after the connection is successfully established should other real-time DDP methods be called. If you comment out the section of code after `connect({})`, things will start working fine. I have been seeing this issue for a long time, since January when I first started contributing, but I don't know how to fix it.

Any help from other contributors would be really helpful.

### Expected behavior

Real-time communication should be initiated only after a successful connection is made.

**Comment by Spiral-Memory** [comment]
Hey @devanshkansagra, this is the issue i was talking about, any help from your side will be greatly appreciated.

**Comment by Spiral-Memory** [comment]
![image](https://github.com/RocketChat/EmbeddedChat/assets/78961432/b1b70fbf-2b42-4038-93cd-754f6f754b7d)

**Comment by devanshkansagra** [comment]
Yea sure I will be working on it

**Comment by Spiral-Memory** [comment]
Let me also explain when we call the connect function defined in `EmbeddedChatApi` in packages/api and how it works. In `EmbeddedChat.js` in packages/react, within useEffect, we register a callback function into authListener. As soon as the authentication status changes (which occurs when notifyAuthListeners is called), a function will be triggered if it detects a user. In this function, we attempt to establish real-time communication using the connect function and the user's details:

![image](https://github.com/RocketChat/EmbeddedChat/assets/78961432/bb9af32f-c52a-4361-b552-77f9d46c7d40)

**Comment by Suvendu-UI** [comment]
can i work on this issue?

**Comment by Spiral-Memory** [comment]
I'll suggest you to work on one issue at a time.. 
You can start working on optimising the sidebars first !

**Comment by r3yc0n1c** [comment]
hey @devanshkansagra are you working on this? If not, I'm willing to fix it.

**Comment by devanshkansagra** [comment]
hey @r3yc0n1c, you can try it, but I don't think this is  currently solvable because on integration side you are using react18 and in the storybook react17 is used so might be due to react versioning this is causing error. This thing we(I and @Spiral-Memory) have came across when I was working on this issue. The ddp error [pr-#600](https://github.com/RocketChat/EmbeddedChat/pulls/600) is actually solved but this websocket still in connecting state error is not solved. This might be due to poor state management or something else causing in the backend side.

**Comment by r3yc0n1c** [comment]
have you tried upgrading storybook to react18 or downgrading the integration side?

**Comment by devanshkansagra** [comment]
Actually I have tried to upgrade it but still I have got same error. Idk whether this is backend side or client side issue

**Comment by devanshkansagra** [comment]
> have you tried upgrading storybook to react18 or downgrading the integration side?

On downgrading the integration this error is resolved

**Comment by devanshkansagra** [comment]
maybe I don't know but when this project was introduced the react17 was very stable and react18 was a new commer.   and earlier the integration was done on v17. we have some integration examples like e2e-react package, it is working on react 18 and you will observe this error over there

**Comment by r3yc0n1c** [comment]
got it, let me try this for v18

**Comment by devanshkansagra** [comment]
Hey @r3yc0n1c check this I am running this e2e-react package which is an EmbeddedChat integration and still there is error when running on react18

![image](https://github.com/user-attachments/assets/76ac9318-e050-4050-9c70-74f70a0db6a5)

**Comment by deepak0x** [comment]
Hey @Spiral-Memory 
Is the issue still open?
Will like to work on it....

**Comment by Spiral-Memory** [comment]
Closing due to inactivity.
